# Generated by Django 6.0.6 on 2026-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_productos_remove_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='usuario',
            new_name='estudiante',
        ),
        migrations.AlterField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
